### PR TITLE
Text File from People's Guide Sacramento

### PR DESCRIPTION
**Pull request by jmwerneke**
Text file to convert to a CSV file for Ohana DB format

### CODE REVIEW

**Comment by femmestem** [comment]
This PR has been sent to the master repo for all projects. Did you mean to send a PR to your fork?

**Comment by jmwerneke** [comment]
yes sorry just saw this...

On Wed, Mar 16, 2016 at 4:42 PM, Christine Feaster <notifications@github.com

**Comment by gh0st** [comment]
Can I close this PR?

**Comment by SilverRat** [comment]
Sure.


Thank you,
Jerry Gray
IT Manager
Department of Technology |Sacramento County<http://www.saccounty.net/>
916.874.5409

**Pull request closed without merging**
